### ISSUE TITLE
Checking various websites compatibility with the proxy server

### ISSUE THREAD

**Issue by Adithya11811** [Adithya11811/ProxyServer#3]
Give a list of all the websites that the proxy sever can handle, If not handling tell us why and find a way of resolving it

**Comment by shawn-exe** [comment]
> Give a list of all the websites that the proxy server can handle, if not handling tell us why and find a way of resolving it

This Issue is resolved through the commit-"9a4c6774b869db11a44db76b7bce3998b852d4f9" 👉  [click here!](https://github.com/search?q=repo%3AAdithya11811%2FProxyServer+9a4c6774b869db11a44db76b7bce3998b852d4f&type=pullrequests)
